name: Deploy Admin Panel Preview

on:
  push:
    branches: [ feature/admin-panel ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages-admin
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests --maxWorkers=2
        env:
          CI: true
          NODE_OPTIONS: "--max_old_space_size=2048"

      - name: Temporarily reduce large data files for build
        run: |
          # Backup original data files
          cp src/constants/galleryData.js src/constants/galleryData.js.backup
          cp src/constants/productsData.js src/constants/productsData.js.backup

          # Create minimal gallery data for build
          echo "export const projectCategories = [];" > src/constants/galleryData.js
          echo "export const galleryProjects = [];" >> src/constants/galleryData.js
          echo "export const getProjectsByCategory = () => [];" >> src/constants/galleryData.js
          echo "export const getAllProjects = () => [];" >> src/constants/galleryData.js
          echo "export const getProjectById = () => null;" >> src/constants/galleryData.js

          # Create minimal products data for build (keep first 3 products only)
          head -50 src/constants/productsData.js > temp_products.js
          echo "]" >> temp_products.js
          echo "" >> temp_products.js
          echo "export default PRODUCTS_DATA" >> temp_products.js
          mv temp_products.js src/constants/productsData.js

      - name: Build project with admin features
        run: npm run build
        env:
          PUBLIC_URL: /eurogranite-website
          REACT_APP_ADMIN_MODE: true
          NODE_OPTIONS: "--max_old_space_size=4096"
          GENERATE_SOURCEMAP: false
          NODE_ENV: production

      - name: Restore original data files
        run: |
          mv src/constants/galleryData.js.backup src/constants/galleryData.js
          mv src/constants/productsData.js.backup src/constants/productsData.js

      - name: Bundle size analysis
        run: npm run bundle:check
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4