name: Deploy Admin Panel Preview

on:
  push:
    branches: [ feature/admin-panel ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages-admin
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests
        env:
          CI: true

      - name: Build project with admin features
        run: npm run build
        env:
          PUBLIC_URL: /eurogranite-website-admin
          REACT_APP_ADMIN_MODE: true

      - name: Bundle size analysis
        run: npm run bundle:check
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4